version: '3.9'

services:
    web:
        build: .
        container_name: "django"
        # command: bash -c 'python manage.py collectstatic --noinput'
        command: python /code/manage.py runserver 0.0.0.0:8000
        # command: bash -c 'gunicorn config.wsgi -b 0.0.0.0:8000'
        volumes:
        - .:/code
        ports:
        - 8000:8000
        depends_on:
        - db_books
        env_file:
            - .env

    db_books:
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
            - ~/.pg/postgres_data/boooks:/var/lib/postgresql/data/
        env_file:
            - .env
#     nginx:
#         build: 
#             dockerfile: ./Dockerfile
#             context: ./docker/nginx
#         container_name: "nginx"
#         volumes:
#         - static_volume:/book/static
#         - media_volume:/book/media

#         depends_on:
#             - web
#         ports:
#             - 80:80

# volumes:
#     static_volume:
#     media_volume:
