version: '3.9'

services:
    staticfiles-api:
        build:
            target: django-static-builder
        image: staticfiles-api:develop
        ports:
        - 8000:8000
        depends_on:
        - db_books
        env_file:
            - .env

    staticfiles-front:
        build:
            target: front
        image: staticfiles-front:develop
        volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - staticfiles-api

        ports:
            - 80:80


    db_books:
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
            - ~/.pg/postgres_data/boooks:/var/lib/postgresql/data/
        env_file:
            - .env
